<?xml version="1.0"?>
<!DOCTYPE games [
  <!ELEMENT games (game)>
  <!ELEMENT game (home-team, ex-team,scores,yellows,reds)>
  <!ELEMENT home-team (#PCDATA)>
  <!ELEMENT ex-team (#PCDATA)>
  <!ELEMENT scores (score*)>
  <!ELEMENT yellows (player*)>
  <!ELEMENT reds (player*)>
  <!ATTLIST game score CDATA "">
  <!ELEMENT score (player)>
  <!ELEMENT player (#PCDATA)>
  <!ELEMENT score EMPTY>
  <!ATTLIST score me CDATA "" type CDATA "" >
]>
<games>
    <game score="1-1">
         <home-team>Roma</home-team>
         <ex-team>Lazio</ex-team>
         <scores>
            <score me="15">
              <player>Klose</player>
            </score>
              <score me="85" type="penalty">
              <player>Tox</player>
            </score>
         </scores>
        <yellows>
           <player>Tox</player>
           <player>Hernanes</player>
        </yellows>
        <reds>
           <player>Kjaer</player>
        </reds>
    </game>
</games>