<?xml version="1.0"?>
<!DOCTYPE channel [
<!ELEMENT channel (item+,title,link,image*,language?,description)>
<!ATTLIST channel version CDATA "">
<!ELEMENT item (title,link,description?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT image (title,link,url)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT url (#PCDATA)>
]>
<channel version="1.0">
    <item>
    	<title>Title for item</title>
      <link> https://www.w3schools.com/xml/xml_dtd_intro.asp</link>
      <description>This is the first item</description>
    </item>
      <title>Title two</title>
      <link>https://www.w3schools.com/xml/xml_dtd_attributes.asp</link>
    <image>
       <title>image</title>
       <link> www/google.com/image.png </link>
       <url>www/google.com/image.png</url>
     </image>
     <language>English</language>
     <description>This is some XML</description>
</channel>
